### ISSUE TITLE
Feature Request: Allow choosing which Overseerr user it uses

### ISSUE THREAD

**Issue by hacshacdgacs** [TegridyTate/Hassarr#2]
As the title states. Currently it logs in as the Admin account which means everything is auto-approved. If it were able to be restricted to a user account it would allow the admin to approve/deny requests from the users

**Comment by TegridyTate** [comment]
This has been added in the newest commit

**Comment by TegridyTate** [comment]
Done

**Comment by LLama92** [comment]
@hacshacdgacs 
GIve the user a display name within overseerr this will correct it.
